-- MySQL Script generated by MySQL Workbench
-- jue 19 abr 2018 07:58:13 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estudiantes` (
  `IdEstudiante` INT(5) ZEROFILL NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`IdEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materias` (
  `idMaterias` INT(4) ZEROFILL NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `UnidadValorativa` INT(2) ZEROFILL NOT NULL,
  `Comentario` VARCHAR(45) NULL,
  PRIMARY KEY (`idMaterias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MateriasXEstudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MateriasXEstudiantes` (
  `IdMateriasEstudiantes` INT NOT NULL AUTO_INCREMENT,
  `IdEstudiante` INT(5) ZEROFILL NOT NULL,
  `IdMateria` INT(4) ZEROFILL NOT NULL,
  `AnioCurso` DATE NOT NULL,
  `Comentario` VARCHAR(45) NULL,
  PRIMARY KEY (`IdMateriasEstudiantes`),
  INDEX `fk_MateriasXEstudiantes_1_idx` (`IdEstudiante` ASC),
  INDEX `fk_MateriasXEstudiantes_2_idx` (`IdMateria` ASC),
  CONSTRAINT `fk_MateriasXEstudiantes_1`
    FOREIGN KEY (`IdEstudiante`)
    REFERENCES `mydb`.`Estudiantes` (`IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MateriasXEstudiantes_2`
    FOREIGN KEY (`IdMateria`)
    REFERENCES `mydb`.`Materias` (`idMaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
